"""Hợp đồng tối thiểu. Thay đổi cần cả nhóm review; không chứa Cypher."""

from typing import Protocol
from app.shared.models.dto import CurrentUser, LessonSummary, AttemptSummary


class QueryExecutor(Protocol):
    def read(self, query: str, **params) -> list[dict]: ...


class IdentityReader(Protocol):
    def current_user(self) -> CurrentUser | None: ...


class ContentReader(Protocol):
    def geometry_graph(self) -> dict[str, list[dict]]: ...
    def lessons(self, grade: int) -> list[LessonSummary]: ...
    def prerequisites(self, lesson_id: str) -> list[LessonSummary]: ...
    def ai_context(self, lesson_id: str) -> list[LessonSummary]: ...


class AssessmentReader(Protocol):
    def attempts(self, user_id: str) -> list[AttemptSummary]: ...


class WriteExecutor(QueryExecutor, Protocol):
    def write(self, query: str, **params) -> list[dict]: ...
    def transaction(self, work): ...


class LearningCatalogReader(Protocol):
    def catalog(self, grade: int) -> list: ...


class ProgressWriter(Protocol):
    def complete_lesson(self, user_id: str, lesson_id: str) -> None: ...
    def start_lesson(self, user_id: str, lesson_id: str) -> None: ...
    def resume_lesson(self, user_id: str) -> LessonSummary | None: ...


class IdentityActions(IdentityReader, Protocol):
    def require_user(self, user_id=None, admin=False) -> CurrentUser: ...
    def login(self, token: str) -> None: ...
    def logout(self) -> None: ...
    def profile(self) -> dict: ...
    def update_profile(self, name, language, avatar_url="") -> None: ...
    def search_users(self, term="") -> list[dict]: ...
    def set_blocked(self, user_id, blocked) -> None: ...
    def enter_demo(self) -> None: ...


class Authentication(Protocol):
    def register(
        self, name, email, password, grade, age, guardian_email=""
    ) -> tuple: ...
    def activate(self, raw, kind) -> str: ...
    def login(self, email, password) -> str: ...
    def request_reset(self, email) -> str | None: ...
    def reset_password(self, raw, password) -> str: ...
    def change_password(self, identity, old, new) -> None: ...


class LearningPath(ProgressWriter, Protocol):
    def levels(self, user_id) -> list: ...
    def catalog_for(self, user_id, grade) -> list: ...
    def breakdown(self, user_id, grade) -> list[dict]: ...
    def change_level(self, grade, confirm_skip=False) -> None: ...
    def access(self, user_id, grade) -> bool: ...
    def refresh(self, user_id) -> None: ...
    def topic_statistics(self, user_id) -> list[dict]: ...
    def review_lessons(self, user_id) -> list[LessonSummary]: ...


# TODO: contract xóa dữ liệu assessment/chat và timestamps/detail answers do Đạt cung cấp.
