CREATE CONSTRAINT user_id IF NOT EXISTS FOR (n:User) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT level_id IF NOT EXISTS FOR (n:Level) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT chapter_id IF NOT EXISTS FOR (n:Chapter) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT topic_id IF NOT EXISTS FOR (n:Topic) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT lesson_id IF NOT EXISTS FOR (n:Lesson) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT quadrilateral_id IF NOT EXISTS FOR (n:Quadrilateral) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT geometryconfig_id IF NOT EXISTS FOR (n:GeometryConfig) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT question_id IF NOT EXISTS FOR (n:Question) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT option_id IF NOT EXISTS FOR (n:Option) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT essayproblem_id IF NOT EXISTS FOR (n:EssayProblem) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT essayhint_id IF NOT EXISTS FOR (n:EssayHint) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT attempt_id IF NOT EXISTS FOR (n:Attempt) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT attemptanswer_id IF NOT EXISTS FOR (n:AttemptAnswer) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT progress_id IF NOT EXISTS FOR (n:Progress) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT chatsession_id IF NOT EXISTS FOR (n:ChatSession) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT chatmessage_id IF NOT EXISTS FOR (n:ChatMessage) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT importlog_id IF NOT EXISTS FOR (n:ImportLog) REQUIRE n.id IS UNIQUE
;
CREATE CONSTRAINT user_email IF NOT EXISTS FOR (u:User) REQUIRE u.email IS UNIQUE
;
CREATE CONSTRAINT level_grade IF NOT EXISTS FOR (l:Level) REQUIRE l.grade IS UNIQUE
;
CREATE CONSTRAINT progress_pair IF NOT EXISTS FOR (p:Progress) REQUIRE (p.user_id, p.level_id) IS UNIQUE
;
